// Generated by `npm run cf-typegen`; committed so the bucket binding type-checks
// without a Cloudflare round trip.
interface CloudflareEnv {
  MEDIA: R2Bucket
  STREAM_ACCOUNT_ID?: string
  CF_API_TOKEN?: string
  CMS_PASSWORD?: string
  R2_PUBLIC_BASE_URL?: string
}
